<?php

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function custom_forms_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
      case 'help.page.custom_forms':
        $output = '';
        $output .= '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('Implements Forms blocks to be included into pages') . '</p>';
        return $output;
  
      default:
    }
  }

  
/**
 * Implements hook_theme().
 */
function custom_forms_theme() {
  return [
    'benefits_request_form_block' => [
      'render element' => 'form',
    ]
  ];
}